### PR TITLE
chore: upgrade node-pre-gyp to fix deprecation warnings

### PR DESCRIPTION
**Pull request by benmccann**
closes https://github.com/vercel/nft/issues/421

it's taken me almost 6 months from starting in https://github.com/vercel/nft/issues/421#issuecomment-2195148286, but this finally fixes it!

### CODE REVIEW

**Review by ijjk — APPROVED** [review]

**Comment by ijjk** [comment]
It looks like we're failing node-gyp test cases with this bump

**Comment by benmccann** [comment]
>  Cannot find module 'consola/basic' from 'node_modules/@mapbox/node-pre-gyp/lib/util/log.js'

Hmm. The library switched from `npmlog` to `consola`. Is there anything special I might have to do in this project relating to dependencies or do you think it's failing for all users of `@mapbox/node-pre-gyp`?

**Review by ijjk — COMMENTED** [review]
Looks like this is an issue with our jest version, bumping to latest might resolve

**Comment by benmccann** [comment]
awesome. thank you. it looks like that worked!

**Review by styfle — APPROVED** [review]

**Review by ijjk — APPROVED** [review]

**Comment by benmccann** [comment]
thank you!! any chance I could get a new release?

**Comment by styfle** [comment]
Using `chore:` skips releases. It probably should have been called `fix:` if you want a semver patch release.

**Pull request merged**
