### PR TITLE
fix: support datadog-pprof

### LINKED ISSUE #410: Add support for `@datadog/pprof`
When building with `output: standalone`, `@datadog/pprof` `prebuilds` gets excluded as the current AST logic introduced in https://github.com/vercel/nft/issues/391 does not handle the case where imports are assigned to a const. 

See `@datadog/pprof` codebase [here](https://github.com/DataDog/pprof-nodejs/blob/main/ts/src/heap-profiler-bindings.ts) on how they assign the CJS import of `node-gyp-build` to a variable, that way we cannot resolve the name to `node-gyp-build` just by inferring the AST node's first argument

## Suggested solution
Instead of modifying the conditionals to handle this case like in #391, just add a special case for `@datadog/pprof` to include the `prebuilds` folder. I have a fix up and will discuss the alternative in more detail here

### PR DESCRIPTION
**Pull request by austinwoon**
Closes #410

## Alternative solution considered
- Modify the case block used to handle `NODE_GYP_BUILD` to account for problem identified in #410. This proved to be tricky as we need to retrieve the value from `findBindings` which involves a walk of the whole tree

## Solution 
Instead of the alternative above, chose to just add a special case for this package

## Automated tests
Just added a conditional `testName === '@datadog-pprof'` to the `foundMatchingBinary` statement so we test the presence of the `prebuilds` folder.

## Manual tests (since the automated tests do not test for presence of `prebuilds` folder
Running `node out/cli.js print node_modules/@datadog/pprof/out/src/index.js` gives me the following FILELIST

```bash
FILELIST:
node_modules/@datadog/pprof/node_modules/node-gyp-build/index.js
node_modules/@datadog/pprof/node_modules/node-gyp-build/package.json
node_modules/@datadog/pprof/node_modules/source-map/lib/array-set.js
node_modules/@datadog/pprof/node_modules/source-map/lib/base64-vlq.js
node_modules/@datadog/pprof/node_modules/source-map/lib/base64.js
node_modules/@datadog/pprof/node_modules/source-map/lib/binary-search.js
node_modules/@datadog/pprof/node_modules/source-map/lib/mapping-list.js
node_modules/@datadog/pprof/node_modules/source-map/lib/mappings.wasm
node_modules/@datadog/pprof/node_modules/source-map/lib/read-wasm.js
node_modules/@datadog/pprof/node_modules/source-map/lib/source-map-consumer.js
node_modules/@datadog/pprof/node_modules/source-map/lib/source-map-generator.js
node_modules/@datadog/pprof/node_modules/source-map/lib/source-node.js
node_modules/@datadog/pprof/node_modules/source-map/lib/util.js
node_modules/@datadog/pprof/node_modules/source-map/lib/wasm.js
node_modules/@datadog/pprof/node_modules/source-map/package.json
node_modules/@datadog/pprof/node_modules/source-map/source-map.js
node_modules/@datadog/pprof/out/src/heap-profiler-bindings.js
node_modules/@datadog/pprof/out/src/heap-profiler.js
node_modules/@datadog/pprof/out/src/index.js
node_modules/@datadog/pprof/out/src/logger.js
node_modules/@datadog/pprof/out/src/profile-encoder.js
node_modules/@datadog/pprof/out/src/profile-serializer.js
node_modules/@datadog/pprof/out/src/sourcemapper/sourcemapper.js
node_modules/@datadog/pprof/out/src/time-profiler-bindings.js
node_modules/@datadog/pprof/out/src/time-profiler.js
node_modules/@datadog/pprof/package.json
node_modules/@datadog/pprof/prebuilds/darwin-arm64/node-102.node
node_modules/@datadog/pprof/prebuilds/darwin-arm64/node-108.node
node_modules/@datadog/pprof/prebuilds/darwin-arm64/node-111.node
node_modules/@datadog/pprof/prebuilds/darwin-arm64/node-115.node
node_modules/@datadog/pprof/prebuilds/darwin-arm64/node-120.node
node_modules/@datadog/pprof/prebuilds/darwin-arm64/node-83.node
node_modules/@datadog/pprof/prebuilds/darwin-arm64/node-88.node
node_modules/@datadog/pprof/prebuilds/darwin-arm64/node-93.node
node_modules/@datadog/pprof/prebuilds/darwin-x64/node-102.node
node_modules/@datadog/pprof/prebuilds/darwin-x64/node-108.node
node_modules/@datadog/pprof/prebuilds/darwin-x64/node-111.node
node_modules/@datadog/pprof/prebuilds/darwin-x64/node-115.node
node_modules/@datadog/pprof/prebuilds/darwin-x64/node-120.node
node_modules/@datadog/pprof/prebuilds/darwin-x64/node-83.node
node_modules/@datadog/pprof/prebuilds/darwin-x64/node-88.node
node_modules/@datadog/pprof/prebuilds/darwin-x64/node-93.node
node_modules/@datadog/pprof/prebuilds/linux-arm64/node-102.node
node_modules/@datadog/pprof/prebuilds/linux-arm64/node-108.node
node_modules/@datadog/pprof/prebuilds/linux-arm64/node-111.node
node_modules/@datadog/pprof/prebuilds/linux-arm64/node-115.node
node_modules/@datadog/pprof/prebuilds/linux-arm64/node-120.node
node_modules/@datadog/pprof/prebuilds/linux-arm64/node-83.node
node_modules/@datadog/pprof/prebuilds/linux-arm64/node-88.node
node_modules/@datadog/pprof/prebuilds/linux-arm64/node-93.node
node_modules/@datadog/pprof/prebuilds/linux-x64/node-102.node
node_modules/@datadog/pprof/prebuilds/linux-x64/node-108.node
node_modules/@datadog/pprof/prebuilds/linux-x64/node-111.node
node_modules/@datadog/pprof/prebuilds/linux-x64/node-115.node
node_modules/@datadog/pprof/prebuilds/linux-x64/node-120.node
node_modules/@datadog/pprof/prebuilds/linux-x64/node-83.node
node_modules/@datadog/pprof/prebuilds/linux-x64/node-88.node
node_modules/@datadog/pprof/prebuilds/linux-x64/node-93.node
node_modules/@datadog/pprof/prebuilds/linuxmusl-x64/node-102.node
node_modules/@datadog/pprof/prebuilds/linuxmusl-x64/node-108.node
node_modules/@datadog/pprof/prebuilds/linuxmusl-x64/node-111.node
node_modules/@datadog/pprof/prebuilds/linuxmusl-x64/node-115.node
node_modules/@datadog/pprof/prebuilds/linuxmusl-x64/node-120.node
node_modules/@datadog/pprof/prebuilds/linuxmusl-x64/node-83.node
node_modules/@datadog/pprof/prebuilds/linuxmusl-x64/node-88.node
node_modules/@datadog/pprof/prebuilds/linuxmusl-x64/node-93.node
node_modules/@datadog/pprof/prebuilds/win32-ia32/node-102.node
node_modules/@datadog/pprof/prebuilds/win32-ia32/node-83.node
node_modules/@datadog/pprof/prebuilds/win32-ia32/node-88.node
node_modules/@datadog/pprof/prebuilds/win32-ia32/node-93.node
node_modules/@datadog/pprof/prebuilds/win32-x64/node-102.node
node_modules/@datadog/pprof/prebuilds/win32-x64/node-108.node
node_modules/@datadog/pprof/prebuilds/win32-x64/node-111.node
node_modules/@datadog/pprof/prebuilds/win32-x64/node-115.node
node_modules/@datadog/pprof/prebuilds/win32-x64/node-120.node
node_modules/@datadog/pprof/prebuilds/win32-x64/node-83.node
node_modules/@datadog/pprof/prebuilds/win32-x64/node-88.node
node_modules/@datadog/pprof/prebuilds/win32-x64/node-93.node
node_modules/delay/index.js
node_modules/delay/package.json
node_modules/p-limit/index.js
node_modules/p-limit/package.json
node_modules/pprof-format/dist/index.js
node_modules/pprof-format/package.json
node_modules/yocto-queue/index.js
node_modules/yocto-queue/package.json
```

We see that the entire `prebuilds` folder is correctly included.

### CODE REVIEW

**Review by styfle — COMMENTED** [review]
Thanks for the PR!

Do you know why prebuilds is not detected?

We fixed this to work with `node-gyp-build` as well as the fork `@aminya/node-gyp-build`

- See https://github.com/vercel/nft/pull/392

I would prefer a fix for the generic case if we can determine what datadog is doing differently here.

**Comment by styfle** [comment]
Looks like we're hitting this `NODE_GYP_BUILD` case, but the AST is not understood and so node-gyp-build is never executed.

https://github.com/vercel/nft/blob/c16e7945c3f3221616567356d9abc2e824bf38cd/src/analyze.ts#L755

**Comment by austinwoon** [comment]
> Looks like we're hitting this `NODE_GYP_BUILD` case correctly, however the AST is not understood and so `node-gyp-build` is never executed.
> 
> https://github.com/vercel/nft/blob/c16e7945c3f3221616567356d9abc2e824bf38cd/src/analyze.ts#L755

Yes, I described why this was the case in the issue [here](https://github.com/vercel/nft/issues/410)

Datadog is using a CJS import and assigning it to a variable. So in the AST, we will not be able to infer the package name from the arguments (the arguments are `findBinding`, `..`, `..` respectively.

I also find that having to manually resolve the arguments via checking the array of args a little hard-codey, so i decided to just have a special case catch all instead for the package to just include `prebuilds` as it seemed simpler. Hope that makes sense!

**Comment by austinwoon** [comment]
> Looks like we're hitting this `NODE_GYP_BUILD` case correctly, however the AST is not understood and so `node-gyp-build` is never executed.
> 
> https://github.com/vercel/nft/blob/c16e7945c3f3221616567356d9abc2e824bf38cd/src/analyze.ts#L755

Could I also check if it would be possible to include a flag to ignore tree shaking modules in a package? I think it would make sense as a catch-all to handle special case like these!

**Review by styfle — COMMENTED** [review]
I think we can revisit the general solution in a new PR and merge this PR once the windows test pass

**Comment by austinwoon** [comment]
> I think we can revisit the general solution in a new PR and merge this PR once the windows test pass

I have removed the sourcemaps outputs from `output.js` since there is no actual need to test for those folders. Could you please rerun the test pipeline? Thank you

**Comment by styfle** [comment]
I took a stab at fixing this properly in PR https://github.com/vercel/nft/pull/419

**Pull request closed without merging**
