### PR TITLE
chore: upgrade argon2

### PR DESCRIPTION
**Pull request by benmccann**
ref https://github.com/vercel/nft/issues/421. I think this should unblock that issue, but I believe there is more required. Would you be able to fix it as a follow up or at least provide some pointers?

### CODE REVIEW

**Review by styfle — COMMENTED** [review]
Since `argon2` is a devDependency, it's not related to https://github.com/vercel/nft/issues/421

That said, its fine to upgrade but it looks like this is causing code coverage to drop which makes me think its no longer testing the code path for argon in special-cases.ts

https://github.com/vercel/nft/blob/bd68351519b29e72a4be2e870893515c8cc0456a/src/utils/special-cases.ts#L21-L26

And more importantly, a the `zeromq-node-gyp` test started failing

https://github.com/vercel/nft/actions/runs/9686185024/job/26738120405?pr=431#step:10:1098

**Comment by benmccann** [comment]
> Since argon2 is a devDependency, it's not related to https://github.com/vercel/nft/issues/421

Could you clarify your comment from https://github.com/vercel/nft/pull/407#issuecomment-2113765135? I thought you were saying the only reason `@mapbox/node-pre-gyp` is in `dependencies` is because `argon2` uses it. The old version of `argon2` depends on it, but the new version doesn't, so it sounded to me like upgrading `argon2` would allow us to remove `@mapbox/node-pre-gyp` thus fixing https://github.com/vercel/nft/issues/421

**Comment by styfle** [comment]
@benmccann My comment was about replacing `@mapbox/node-pre-gyp` with our own implementation since its only using `find()`. I was using argon2 as an example of one of the packages that uses `@mapbox/node-pre-gyp` since I've never used it before so I had to look at how its used in real packages.

**Comment by benmccann** [comment]
Ah, I see. Thanks for clarifying. I'll go ahead and close this then since it won't help with my goal of resolving https://github.com/vercel/nft/issues/421

**Pull request closed without merging**
